<div><div style="background-color:#cccccc;min-height:auto"><table align="center" bgcolor="#FFFFFF" border="0" cellpadding="0" cellspacing="0" height="auto" width="600"><tbody><tr><td valign="top"> <img src="http://www.educacao.ba.gov.br/sites/default/files/imagecache/Album_Foto_Main_Colorbox/midiateca/imagens/2013/infomailespacoaberto01.jpg" width="600"></td></tr><tr><td bgcolor="#E5F1CD" valign="top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <table align="center" border="0" width="90%">
<tbody><tr><td><div align="center"><div align="center"><span><font color="#274425" face="Arial, Helvetica, sans-serif" size="3"><b>Sua inscrição na seleção de vídeos para compor o acervo da TV Anísio Teixeira foi realizada com sucesso.</b></font></span><br></div><span></span></div><span><font color="#274425" face="Arial, Helvetica, sans-serif" size="3"><b><br></b></font></span><div align="justify"><span><font color="#274425" face="Arial, Helvetica, sans-serif" size="3">Toda comunicação entre </font></span><span><font color="#274425" face="Arial, Helvetica, sans-serif" size="3"><span><font color="#274425" face="Arial, Helvetica, sans-serif" size="3">TV Anísio Teixeira e </font></span>você será realizada via e-mail. Por esta razão, é importante verificar sua caixa de mensagens com frequência ou acessar o Portal da Educação (<a href="http://www.educacao.ba.gov.br" target="_blank">www.educacao.ba.gov.br</a>).&nbsp;</font></span><span>&nbsp;</span></div><span></span><font color="#274425" face="Arial, Helvetica, sans-serif" size="3"></font></td></tr></tbody></table>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <table align="center" border="0" height="280" width="540">
<tbody><tr><td valign="top"><p style="margin:0px" align="justify"><font color="#666666" face="Arial, Helvetica, sans-serif" size="3"><b><font color="#003300"><br></font></b></font></p><p style="margin:0px" align="justify"><font color="#666666" face="Arial, Helvetica, sans-serif" size="3"><b><font color="#003300">Aproveite e explore as possibilidades de interação no Espaço Aberto!</font> </b><br></font></p><ul><li>
<font color="#666666"><font size="3"><font face="Arial, Helvetica, sans-serif">Álbum de fotos</font></font></font></li><li><font color="#666666"><font size="3"><font face="Arial, Helvetica, sans-serif">Blog pessoal</font></font></font></li><li><font color="#666666"><font size="3"><font face="Arial, Helvetica, sans-serif">Comunidades</font></font></font></li><li><font color="#666666"><font size="3"><font face="Arial, Helvetica, sans-serif">Fóruns <br></font></font></font></li><li><font color="#666666"><font size="3"><font face="Arial, Helvetica, sans-serif">Chat com colegas</font></font></font></li><li><font color="#666666"><font size="3"><font face="Arial, Helvetica, sans-serif">Busca geral</font></font></font></li></ul></td></tr><tr><td align="center" bgcolor="#E5F1CD"><a target="_blank" href="http://ambiente.educacao.ba.gov.br"><span></span></a><p style="margin:0px"><a target="_blank" href="http://ambiente.educacao.ba.gov.br"><font size="4"></font></a><font size="4"><a target="_blank"><font color="#274425" face="Arial, Helvetica, sans-serif"><b>http://</b></font><font color="#274425" face="Arial, Helvetica, sans-serif"><b>ambiente.educacao</b></font><font color="#274425" face="Arial, Helvetica, sans-serif"><b>.ba.gov.br</b></font></a></font></p></td></tr><tr><td align="center" bgcolor="#E5F1CD">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <table border="0" height="41" width="388"><tbody><tr><td style="border-radius:7px" align="center" bgcolor="#009900" height="30">
<font size="4"><b><font color="#ffffff" face="Arial, Helvetica, sans-serif"><a target="_blank" style="color:#fff;text-decoration:none">Baixe agora o Guia do Espaço Aberto!</a></font></b></font></td>
</tr></tbody></table></td></tr><tr><td align="center" bgcolor="#E5F1CD" valign="middle"><br></td></tr></tbody></table></td></tr><tr><td bgcolor="#E5F1CD"><br></td></tr><tr><td bgcolor="#E5F1CD">&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; <span></span><table border="0" width="100%">
<tbody><tr><td width="5%">&nbsp;</td><td width="15%"><img src="http://www.educacao.ba.gov.br/sites/default/files/imagecache/Album_Foto_Main_Colorbox/midiateca/imagens/2013/infomailespacoaberto04.png"></td><td align="center" width="26%">
<img src="http://www.educacao.ba.gov.br/sites/default/files/imagecache/Album_Foto_Main_Colorbox/midiateca/imagens/2013/infomailespacoaberto05.png"></td><td align="center" width="18%"><img src="http://www.educacao.ba.gov.br/sites/default/files/imagecache/Album_Foto_Main_Colorbox/midiateca/imagens/2013/infomailespacoaberto06.png"></td>
<td align="right" width="32%"><img src="http://www.educacao.ba.gov.br/sites/default/files/imagecache/Album_Foto_Main_Colorbox/midiateca/imagens/2013/infomailespacoaberto07.png"></td><td width="4%">&nbsp;</td></tr></tbody></table>
</td></tr></tbody></table></div><span><font color="#888888">
</font><span><font color="#888888">
</font><span><font color="#888888">
</font></span></span></span></div>
